### ISSUE TITLE
Meet-Up Notes not carrying over from android app to the dispatch dashboard.

### ISSUE THREAD

**Issue by thomasaviles** [thenewtricks/thenewtricks.github.io#2]
Meet-Up Notes are not carrying over from android app to the dispatch dashboard.

After setting up the Meet-Up and Dropoff Locations, Meeting Point Notes are entered, but they do not appear in the Notes section of the Dispatch Dashboard.

**Comment by tylrtrmbl** [comment]
I just gave you access to the Balto team. Can you copy this bug over the Android repo?

Thanks @thomasaviles. :wink:
